spring:
 jwt:
  secret: f4b1a5db731bc1d1e31a9f05e0e1d076f0c9f86bb4007e08d71099d3927e7bae
 mail:
  host: smtp.gmail.com
  port: 587
  username: springb88t@gmail.com
  password: epzssrjpwhrecvvw
  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true
      required: true
     connectiontimeout: 5000
     timeout: 5000
     writetimeout: 5000
   auth-code-expiration-millis: 1800000